<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerFluentStaticInitFcrm6ba88f1695515329cfc7e4b26033cc69
{
    public static $prefixLengthsPsr4 = array (
        'F' =>
        array (
            'FluentEmogrifier\Vendor\\TijsVerkoyen\\CssToInlineStyles\\' => 55,
            'FluentEmogrifier\Vendor\\Symfony\\Component\\CssSelector\\' => 54,
        )
    );

    public static $prefixDirsPsr4 = array (
        'FluentEmogrifier\Vendor\\TijsVerkoyen\\CssToInlineStyles\\' =>
        array (
            0 => __DIR__ . '/..' . '/tijsverkoyen/css-to-inline-styles/src',
        ),
        'FluentEmogrifier\Vendor\\Symfony\\Component\\CssSelector\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/css-selector',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerFluentStaticInitFcrm6ba88f1695515329cfc7e4b26033cc69::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerFluentStaticInitFcrm6ba88f1695515329cfc7e4b26033cc69::$prefixDirsPsr4;
            $loader->classMap = ComposerFluentStaticInitFcrm6ba88f1695515329cfc7e4b26033cc69::$classMap;

        }, null, ClassLoader::class);
    }
}
