<?php

// autoload.php @generated by Composer (init/static class names hardened — see note)

// FluentCart and several other Fluent plugins ship this exact same php-scoped
// Emogrifier bundle. Composer's generated autoloader-init class name is identical
// across those copies, and because require_once dedupes by file path (not class
// name) the second plugin to load fataled with:
//   "Cannot declare class FluentEmogComposerAutoloaderInit... already in use".
// To stay collision-proof, this plugin's init/static classes are namespaced with
// an "Fcrm" marker (see composer/autoload_real.php + autoload_static.php) so they
// can never clash with another plugin's copy. The shared library prefix
// (FluentEmogrifier\Vendor\...) is intentionally left unchanged so the actual
// inliner classes are still reused once any plugin has loaded them — see the
// class_exists() short-circuit in ../../Emogrifier.php.
if (!class_exists('FluentEmogComposerAutoloaderInitFcrm6ba88f1695515329cfc7e4b26033cc69', false)) {
    require_once __DIR__ . '/composer/autoload_real.php';
}
return FluentEmogComposerAutoloaderInitFcrm6ba88f1695515329cfc7e4b26033cc69::getLoader();
