<?php

// Auto generated by wpfluent Installer.

return array(
    'name'           => 'Fluent Crm',
    'slug'           => 'fluent-crm',
    'domain_path'    => '/language',
    'text_domain'    => 'fluent-crm',
    'hook_prefix'    => 'fluentcrm_',
    'rest_namespace' => defined('FLUENTCRM_REST_NAMESPACE') ? FLUENTCRM_REST_NAMESPACE : 'fluent-crm',
    'rest_version'   => 'v2',
    'env' => 'production',
);
